"""add column is super admin

Revision ID: 8d9ad0c7f23a
Revises: 2bc16ad1e04a
Create Date: 2023-10-02 16:20:45.787083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9ad0c7f23a'
down_revision = '2bc16ad1e04a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
