"""add delete column

Revision ID: afb27225ef3d
Revises: b51a647b6220
Create Date: 2023-10-03 14:42:54.529135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb27225ef3d'
down_revision = 'b51a647b6220'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'delete_at')
    # ### end Alembic commands ###
