"""add new columns product

Revision ID: b51a647b6220
Revises: d45def7d6bee
Create Date: 2023-10-02 23:02:01.294215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51a647b6220'
down_revision = 'd45def7d6bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('create_by', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('update_by', sa.Integer(), nullable=True))
    op.drop_constraint('products_brand_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['create_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'users', ['update_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_brand_fkey', 'products', 'brands', ['brand'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'update_by')
    op.drop_column('products', 'create_by')
    op.drop_column('products', 'brand_id')
    # ### end Alembic commands ###
